### ISSUE TITLE
Some tunables are missing, just found some of them

### ISSUE THREAD

**Issue by Apokalypt** [Wildbrick142/V-Tunable-Names#8]
Hi,

With scripts I was able to find all hashes of tunables names that are missing. After few attempts I was able to find some of them (still missing hundreds of them XD) :
- discount_female_glasses_black_lézard_classics
- discount_female_glasses_two_tone_lézard_classics
- discount_female_glasses_brown_marble_lézard_classics
- discount_female_glasses_multicolored_lézard_classics
- discount_female_glasses_orange_lézard_classics
- discount_female_glasses_baby_blue_lézard_classics
- discount_female_glasses_red_lézard_classics
- discount_female_glasses_lime_lézard_classics
- discount_female_glasses_black_lézard_hipsters
- discount_female_glasses_blue_lézard_hipsters
- discount_female_glasses_marble_lézard_hipsters
- discount_female_glasses_two_tone_lézard_hipsters
- discount_female_glasses_red_lézard_hipsters
- discount_female_glasses_orange_lézard_hipsters
- discount_female_glasses_fuchsia_lézard_hipsters
- discount_female_glasses_brown_lézard_hipsters

I provide the list in the order they appear in the tuneables_processing script if you want to check.

**Comment by Apokalypt** [comment]
I didn't see this file sorry

To answer you, I use the decompiled scripts from this repo: https://github.com/root-cause/v-decompiled-scripts
In the tuneables_processing.c script there is the hash of these values (around line 29000). Maybe they were added during the last update? Or am I wrong and not looking at the right file?

**Comment by Wildbrick142** [comment]
there's some really weird stuff going on with these names. they *are* all correct and *do* exist, this can be verified through a certain source that shall not be mentioned, but the hashes do not match up for some reason.

for example `Global_262145.f_2200[96]` is `discount_female_glasses_black_lézard_classics`. in the decompiled scripts the hash for that name is -36793094, while openiv says the hash is -1131129357, and codewalker & joaat hash utility (and also pretty much any online generator on first page of google search) say it's -891564011

i think it's the é in those names messing with it. i feel like unless someone figures out the exact joaat algorithm that the devs use and everyone updates the tools accordingly, these names are gonna be stuck in limbo. i could still add them to the list for posterity, but the decompilers and other hash generators are gonna continue to throw a blank until that issue is looked into.

**Comment by Apokalypt** [comment]
Honestly, I'm pretty sure that the problem comes from the encoding used. My joaat script works well and give me the right hash for all of these tunables (100% sure due to the source)

![Screenshot 2023-01-11 095828](https://user-images.githubusercontent.com/58733915/211762347-a4e7dffc-d113-4878-a632-ddadcde80fb0.png)

(I just update my old message to remove sources)

**Comment by PLTytus** [comment]
This one works, at least for `discount_female_glasses_black_lézard_classics` but I am trying to find Python implementation which works.

C:
```
#include <stdint.h>

uint32_t joaat(const char * s){
    uint32_t hash = 0;
 
    for (; *s; ++s){
        hash += *s;
        hash += (hash << 10);
        hash ^= (hash >> 6);
    }
 
    hash += (hash << 3);
    hash ^= (hash >> 11);
    hash += (hash << 15);
 
    return hash;
}

int main(){
    printf("%d", joaat("discount_female_glasses_black_lézard_classics"));
}
```

**Comment by Wildbrick142** [comment]
everything should be correct now. thanks! let me know if there's more names like this that i missed
